package org.example.server.enums;
//Akmal aka
public enum State {
    START, PHONE_NUMBER, MAIN_PAGE, CHOOSE_CATEGORY, ENTER_CATEGORY_NAME, ENTER_PRODUCT_NAME, CHOOSE_PRODUCT, ENTER_PRODUCT_PRICE, ENTER_PRODUCT_URL, CHOOSE_MAIN_PAGE_CATEGORY, PRESS_CATEGORY_BUTTON, ADD_CATEGORY, DELETE_CATEGORY, ENTER_NAME

}
